### ISSUE TITLE
问一下DATABASE_URL变量填什么啊

### ISSUE THREAD

**Issue by ilhsyysyk** [Clansty/Q2TG#19]
![image](https://user-images.githubusercontent.com/41326182/174975993-c4ef295e-b170-4531-86b0-ec1fa12f84f0.png)
变量：
DATABASE_URL=postgres://user:password@postgres/db_name
我应该填什么啊，没有看明白

**Comment by THU-Pieris** [comment]
你如果没有改docker-compose.yaml里的postgres里的东西的话（见以下代码），这里就不用改，默认值就好了。
```
  postgres:
    image: postgres
    container_name: postgresql_q2tg
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
```
