### ISSUE TITLE
可能需要升级OICQ。

### ISSUE THREAD

**Issue by yuioto** [Clansty/Q2TG#47]
RT.

```log
2022-09-03T14:11:57.404741067Z [温馨提示]当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面
```
![图片](https://user-images.githubusercontent.com/68138727/188274392-f957e20e-7e20-424c-80f7-57c46ccc3fe3.png)

**Comment by yuioto** [comment]
附位置文件：
已经略去关键key等。

```yaml
version: "3.8"
services:
  # 如果有现成的 Postgresql 实例，可以删除这一小节
  postgres:
    image: postgres
    container_name: postgresql_q2tg
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  q2tg:
    image: ghcr.io/clansty/q2tg:raincandy
    container_name: main_q2tg
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    environment:
      - TG_API_ID=
      - TG_API_HASH=
      - TG_BOT_TOKEN=
      - DATABASE_URL=
      - CRV_API=https://chatrecord-viewer-frontend-4ga.pages.dev/api
      - CRV_KEY=
      # 如果需要通过代理联网，那么设置下面两个变量
      # - PROXY_IP=127.0.0.1
      # - PROXY_PORT=20170
```
