### ISSUE TITLE
Fixed PostgreSQL version?

### ISSUE THREAD

**Issue by yuioto** [Clansty/Q2TG#89]
## Problem
I got an error about PostgreSQL.

``` log
The data directory was initialized by PostgreSQL version 14, which is not compatible with this version 15.1 (Debian 15.1-1.pgdg110+1).
```
## Solution
I did that.
```yaml
    # image: postgres
    image: postgres:14-alpine
```
from: plankanban/planka#312

This helped me solve the problem.

## Improve

I think we may need fixed PostgreSQL version. To help others avoid this problem, or guide them how to upgrade PostgreSQL version.

## My yaml file. (No key)

```yaml
version: "3.8"
services:
  # 如果有现成的 Postgresql 实例，可以删除这一小节
  postgres:
    # image: postgres
    image: postgres:14-alpine
    container_name: postgresql_q2tg
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  q2tg:
    image: ghcr.io/clansty/q2tg:sha-efc3f07
#    image: ghcr.io/clansty/q2tg:raincandy
    container_name: main_q2tg
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data
    environment:
      - TG_API_ID=
      - TG_API_HASH=
      - TG_BOT_TOKEN=
      - DATABASE_URL=
      - CRV_API=
      - CRV_KEY=
      # 如果需要通过代理联网，那么设置下面两个变量
      # - PROXY_IP=127.0.0.1
      # - PROXY_PORT=20170
```
